# AUTHOR: Ditz Guntlisbergen (TheD1TZ)
# WIKI: https://github.com/TheD1TZ/ProHub/wiki
# Copyright Ditz Guntlisbergen 2021. All rights reserved.


# Check for latest SpigotMC updates.

check-updates: true


# List any worlds you want ProHub to manage.

enabled-worlds:

  worlds:
    - world
    - lobby
    - spawn


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | Join Leave FirstJoin Messages            |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


JoinMessage:

  enabled: true
  message: '%player% joined!'

FirstJoin:

  enabled: true
  message: 'Welcome %player%!'

LeaveMessage:

  enabled: true
  message: '%player% left!'


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | MOTD Message                             |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

MOTD:
  enabled: true
  message:
    - '&7-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'
    - '&eWelcome to &lProHub'
    - ''
    - '&e&lWebsite: &fprohub.com'
    - '&e&lDiscord: &fprohub.com/discord'
    - ''
    - '&7-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | Player Hub/Spawn/Lobby                   |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

Lobby:

  enabled: true
  location:
    x: ''
    y: ''
    z: ''


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | Scoreboard                               |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


Scoreboard:

  enabled: true

  title: ''

  lines:
    - ''
    - ''
    - ''
    - ''
    -


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | TABLIST                                  |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


Tablist:

  enabled: true

  header:
    - ''
    - ''
    - ''
    - ''

  footer:
    - ''
    - ''
    - ''
    - ''
    - ''

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | World Settings                           |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#



WorldSettings:

  # Player

  disable_hunger_loss: true

  disable_fall_damage: true

  disable_player_pvp: true

  disable_void_death: true

  disable_fire_damage: true

  disable_drowning: true



  # Misc

  disable_weather_change: true

  disable_death_message: true

  disable_mob_spawning: true



  # Item entities

  disable_item_drop: true

  disable_item_pickup: true



  # Blocks

  disable_block_break: true

  disable_block_place: true

  disable_block_interact: true

  disable_block_burn: true

  disable_block_fire_spread: true
