# AUTHOR: Ditz Guntlisbergen (TheD1TZ)
# WIKI: https://github.com/TheD1TZ/ProHub/wiki
# Copyright Ditz Guntlisbergen 2021. All rights reserved.


# Check for latest SpigotMC updates.

check-updates: true

# Set the prefix of the plugin!

Prefix: "&e&lProHub &7&l| "


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | Join Leave FirstJoin Messages            |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


JoinMessage:

  enabled: true
  message: "&7[&a+&7] &f%player_name% joined!"

FirstJoin:

  enabled: true
  message: "%player_name% joined for the first time!"

LeaveMessage:

  enabled: true
  message: "&7[&c-&7] &f%player_name% left!"


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | Title Message                            |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


Title:

  enabled: true
  title: "&f&lWelcome &e&l%player_name%"
  subtitle: "&fto &e&lProHub"

  fadein: 15
  duration: 55
  fadeout: 15


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | MOTD Message                             |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

MOTD:

  enabled: true

  message:
    - "&7-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
    - "&eWelcome to &lProHub"
    - ""
    - "&e&lWebsite: &fprohub.com"
    - "&e&lDiscord: &fprohub.com/discord"
    - ""
    - "&7-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | Server Hub/Spawn/Lobby                   |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

Lobby:

  enabled: true
  world:
  location:
    x:
    y:
    z:
    yaw:
    pitch:

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | JumpPads                                 |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

JumpPad:

  enabled: true

  message: true
  launch-message: "&eWooooosh!"

  #Get als sounds of Minecraft here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sounds: true
  sound: "ENTITY_FIREWORK_ROCKET_LAUNCH"

  #Get al Minecraft blocks here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  topblock: "STONE_PRESSURE_PLATE"
  underblock: "REDSTONE_BLOCK"

  y-velocity: 2
  velocity-multiplier: 2





# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | TABLIST                                  |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


Tablist:

  enabled: true

  # Should we refresh the tablist (update placeholders)?
  refresh:
    enabled: true
    rate: 400 # In ticks (20 ticks = 1 second)

  header:
    - "&7-=&e&lProHub&7=-"
    - "&7This is a second line"
    - "&7Change these lines in the config file!"
    - ""

  footer:
    - ""
    - "&7This is a footer change this line in the config file!"
    - "&7This a nother line"
    - "&7You can also use placeholders &l(PlaceholderAPI needed!)"


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | Scoreboard      THIS FEATURE IS W.I.P    |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


Scoreboard:

  enabled: true

  title: "&7-=&e&lProHub&7=-"

  lines:
    - ""
    - "Player: %player_name%"
    - ""
    - "Economy: %%"
    - ""
    - ""
    - ""
    -

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | Boss Bar          THIS FEATURE IS W.I.P  |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


BossBar:

  enabled: false
  title:
    - ""

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

# | World Settings                           |

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#



WorldSettings:

  # Player

  disable_hunger_loss: true

  disable_fall_damage: true

  disable_player_pvp: true

  disable_void_death: true

  disable_fire_damage: true

  disable_drowning: true



  # Misc

  disable_weather_change: true

  disable_death_message: true



  # Item entities

  disable_item_drop: true

  disable_item_pickup: true



  # Blocks

  disable_block_break: true

  disable_block_place: true

  disable_block_interact: true

  disable_block_burn: true

  disable_block_fire_spread: true
