name: ProHub
version: 0.2
main: net.neromc.prohub.main
api-version: 1.16
authors: [ DitzGuntlisbergen ]
description: A basic hub plugin made by NeroMC Development
softdepend:
  - PlaceholderAPI
website: neromc.net
commands:
  prohub:
    description: The main command for ProHub.
  spawn:
    description: Send the player to the server spawnpoint.
    aliases:
      - lobby
      - hub